### ISSUE TITLE
Exception Cannot deserialize instance of `Class` out of START_ARRAY token

### ISSUE THREAD

**Issue by davidegph** [americanexpress/nodes#26]
Hi,

I am trying to use Nodes to query my GraphQL server; this is the query,

```
GraphQLTemplate graphQLTemplate = new GraphQLTemplate();

GraphQLRequestEntity requestEntity = GraphQLRequestEntity.Builder()
            .url("http://localhost:32806/graphql")
            .arguments(new Arguments("dishes", new Argument<String>("chef_id", "chef_1")), new Arguments("dishes", new Argument<String>("name", "Pizza")))
            .request(Dish.class)
            .build();
System.out.println(requestEntity.getRequest());
GraphQLResponseEntity<Dish> responseEntity = graphQLTemplate.query(requestEntity, Dish.class);
```

This is the model,

```
@GraphQLProperty(name="dishes", arguments = {@GraphQLArgument(name = "chef_id"), @GraphQLArgument(name = "dish_id")})
public class Dish
{
   
    private String chef_id;
    private String dish_id;
    private String name;
    private String description;

...getters and setters...
}
```

This is the schema,

`dishes(chef_id: String! dish_id: String name: String limit: Int = 100 offset: Int = 0 columnToSort: SortDishColumn = NAME order: OrderBy = DESCENDING): [Dish]!`

The query that Nodes generates is,

`query { dishes (chef_id:"chef_1", name:"Pizza") { chef_id name description dish_id } } `

The query does work when used with graphiql, and it is exactly what I am expecting from it. However, the code throws an exception every time,

```
Exception in thread "main" GraphQLException{message='null', status='200', description='Cannot deserialize instance of `org.[... my addition].models.Dish` out of START_ARRAY token
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.aexp.nodes.graphql.Wrapper["data"])', errors=null}
	at io.aexp.nodes.graphql.Fetch.send(Fetch.java:84)
	at io.aexp.nodes.graphql.GraphQLTemplate.execute(GraphQLTemplate.java:83)
	at io.aexp.nodes.graphql.GraphQLTemplate.query(GraphQLTemplate.java:42)
```

Any idea of what I am doing wrong?

Thank you for your help.

**Comment by chemdrew** [comment]
Hi @davidegph,

Great question, this is actually something I need to update the docs with as it's a common problem that isn't very clear. Fortunately, there is a simple way to handle this!

```
public class Dish {
    private String chef_id;
    private String dish_id;
    private String name;
    private String description;

...getters and setters...
}
```

```
public class Dishes {
  @GraphQLArguments({
    @GraphQLArgument(name = "chef_id"),
    @GraphQLArgument(name = "dish_id")
    @GraphQLArgument(name = "name")
  })
  private List<Dish> dishes;

...getter and setter...
}
```

```
GraphQLTemplate graphQLTemplate = new GraphQLTemplate();

GraphQLRequestEntity requestEntity = GraphQLRequestEntity.Builder()
            .url("http://localhost:32806/graphql")
            .arguments(new Arguments("dishes", new Argument<String>("chef_id", "chef_1"), new Argument<String>("name", "Pizza")))
            .request(Dishes.class)
            .build();
System.out.println(requestEntity.getRequest());
GraphQLResponseEntity<Dishes> responseEntity = graphQLTemplate.query(requestEntity, Dishes.class);
```

Hope this helps!

**Comment by davidegph** [comment]
Thank you for your help Andrew! I was able to query my graphql schema thanks to your suggestions.

**Comment by mario-martinez-se** [comment]
Hi, I've been trying this example and for some reason it throws a NPE.
This is the code I am trying (copied from here with small modifications as I am running it from groovy instead of Java)
```
public class Dish {
    String chef_id;
    String dish_id;
    String name;
    String description;
}

public class Dishes {
  @GraphQLArguments([
    @GraphQLArgument(name = "chef_id"),
    @GraphQLArgument(name = "dish_id"),
    @GraphQLArgument(name = "name")
  ])
  List<Dish> dishes;
}

GraphQLTemplate graphQLTemplate = new GraphQLTemplate();

GraphQLRequestEntity requestEntity = GraphQLRequestEntity.Builder()
            .url("http://localhost:32806/graphql")
            .arguments(new Arguments("dishes", new Argument<String>("chef_id", "chef_1"), new Argument<String>("name", "Pizza")))
            .request(Dishes.class)
            .build();
System.out.println(requestEntity.getRequest());
GraphQLResponseEntity<Dishes> responseEntity = graphQLTemplate.query(requestEntity, Dishes.class);

**Comment by debdiptahalder-4tigo** [comment]
Hi the above solution is not working for me. I am still getting the same issue . I am not able to understand what to send in the arguments if the API does not take any arguments.
